### ISSUE TITLE
Peer to Peer review

### ISSUE THREAD

**Issue by mnaibei** [kwesiObuobi/Leaderboard#4]
Hello Kwesi,

- Great job working on this project. The code structure is good and easily understandable. :ok_hand:
- I just have one issue I have spotted. In your index.css there is some code commented out. 
- Please remove it if you are not using the code. :point_down:
https://github.com/kwesiObuobi/Leaderboard/blob/023faaae080b8ddcae384095ed889f4b86d25da2/src/index.css#L124-L127

- Also, to improve UX, please add a visual cue that alerts the user when the form has been submitted.

**Comment by kwesiObuobi** [comment]
Thanks, @mnaibei 😊 
- Unused CSS code is removed now
- To improve the UX, I've added a flash message after the form is submitted👍🏽
